[package]
name = "ferryx-build"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ferryx-parser = { path = "../ferryx-parser" }
ferryx-python = { path = "../ferryx-python" }
ferryx-ir = { path = "../ferryx-ir" }
serde_json.workspace = true

