use ferryx_ir::{IrClass, IrImpl, IrMethod, IrPackage, TypeRef};
use ferryx_rewrite::{default_python_rewrite_pipeline, RewriteContext};

#[derive(Debug, Clone)]
pub struct EmittedFile {
    pub path: String,
    pub content: String,
}

#[derive(Debug, Clone)]
pub struct TsEmission {
    pub files: Vec<EmittedFile>,
}

pub fn emit_typescript(package: &IrPackage) -> TsEmission {
    let mut package = package.clone();
    default_python_rewrite_pipeline().run(&mut package, &RewriteContext::default());

    let mut index_ts = String::new();
    let mut client_ts = String::new();
    index_ts.push_str("/* generated by ferryx */\n");
    client_ts.push_str("/* generated by ferryx */\n");
    client_ts.push_str("export class FerryxClient {\n  constructor(private baseUrl: string) {}\n}\n\n");

    for module in &package.modules {
        for class in &module.classes {
            let methods = methods_for_class(class, &module.impls);
            index_ts.push_str(&render_class(class, &methods));
            index_ts.push('\n');
        }
    }

    let package_json = serde_json::json!({
        "name": package.name,
        "version": "0.1.0",
        "type": "module",
        "main": "index.ts",
        "exports": { ".": "./index.ts" }
    });
    let tsconfig = serde_json::json!({
        "compilerOptions": {
            "target": "ES2022",
            "module": "ES2022",
            "moduleResolution": "Bundler",
            "strict": true,
            "declaration": true
        },
        "include": ["*.ts"]
    });

    TsEmission {
        files: vec![
            EmittedFile {
                path: "index.ts".into(),
                content: index_ts,
            },
            EmittedFile {
                path: "client.ts".into(),
                content: client_ts,
            },
            EmittedFile {
                path: "package.json".into(),
                content: serde_json::to_string_pretty(&package_json).expect("serialize package.json"),
            },
            EmittedFile {
                path: "tsconfig.json".into(),
                content: serde_json::to_string_pretty(&tsconfig).expect("serialize tsconfig"),
            },
        ],
    }
}

fn render_class(class: &IrClass, methods: &[IrMethod]) -> String {
    let mut out = String::new();
    out.push_str(&format!("export class {} {{\n", class.name));
    for field in &class.fields {
        out.push_str(&format!("  {}: {};\n", field.name, map_type(&field.ty)));
    }
    if class.fields.is_empty() {
        out.push_str("  // no fields\n");
    }
    out.push_str("  constructor(init: Partial<");
    out.push_str(&class.name);
    out.push_str(">) { Object.assign(this, init); }\n");
    for method in methods {
        out.push_str("  ");
        if method.is_async {
            out.push_str("async ");
        }
        out.push_str(&method.name);
        out.push('(');
        out.push_str(
            &method
                .params
                .iter()
                .map(|p| format!("{}: {}", p.name, map_type(&p.ty)))
                .collect::<Vec<_>>()
                .join(", "),
        );
        out.push_str("): ");
        let ret = map_type(&method.output);
        if method.is_async {
            out.push_str(&format!("Promise<{ret}>"));
        } else {
            out.push_str(&ret);
        }
        out.push_str(" {\n");
        if method.error.is_some() {
            out.push_str("    throw new Error(\"Projected from Rust Result<T, E>\");\n");
        } else {
            out.push_str("    throw new Error(\"runtime binding required\");\n");
        }
        out.push_str("  }\n");
    }
    out.push_str("}\n");
    out
}

fn methods_for_class(class: &IrClass, impls: &[IrImpl]) -> Vec<IrMethod> {
    let mut out = Vec::new();
    for imp in impls {
        let target = imp.target.rust.replace(' ', "");
        if target.ends_with(&class.name) || target == class.name {
            out.extend(imp.methods.clone());
        }
    }
    out
}

fn map_type(ty: &TypeRef) -> String {
    let rust = ty.rust.replace(' ', "");
    if rust == "String" || rust == "&str" {
        return "string".into();
    }
    if ["f32", "f64", "i32", "i64", "u32", "u64", "usize", "isize"].contains(&rust.as_str()) {
        return "number".into();
    }
    if rust == "bool" {
        return "boolean".into();
    }
    if let Some(inner) = rust.strip_prefix("Vec<").and_then(|s| s.strip_suffix('>')) {
        return format!("{}[]", map_type(&TypeRef { rust: inner.into() }));
    }
    if let Some(inner) = rust.strip_prefix("Option<").and_then(|s| s.strip_suffix('>')) {
        return format!("{} | null", map_type(&TypeRef { rust: inner.into() }));
    }
    rust
}

