[package]
name = "cargo-ferryx"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ferryx-build = { path = "../ferryx-build" }
ferryx-ir = { path = "../../core/ferryx-ir" }
ferryx-parser = { path = "../../core/ferryx-parser" }
ferryx-rewrite = { path = "../../core/ferryx-rewrite" }
ferryx-runtime = { path = "../../core/ferryx-runtime" }
ferryx-target = { path = "../../core/ferryx-target" }
ferryx-typescript = { path = "../../emitters/ferryx-typescript" }
ferryx-wasm = { path = "../../emitters/ferryx-wasm" }
ferryx-openapi = { path = "../../emitters/ferryx-openapi" }
ferryx-grpc = { path = "../../emitters/ferryx-grpc" }
owo-colors.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true

